catch() 方法返回一个Promise (en-US)，并且处理拒绝的情况。它的行为与调用Promise.prototype.then(undefined, onRejected) 相同。
(事实上, calling obj.catch(onRejected) 内部calls obj.then(undefined, onRejected)).
